import type { HydroRegistry } from './types';

const defaultTimestamp = '2026-05-14T12:00:00.000Z';

export const defaultHydroRegistry: HydroRegistry = {
  poço: [
    {
      id: 'well-brejinho',
      code: 'POC-001',
      category: 'poço',
      name: 'Poço Brejinho',
      location: 'Zona 1 - Brejinho',
      status: 'atenção',
      responsible: 'Operador Hidráulico',
      flowRate: 72,
      reservoirLevel: 68,
      powerHp: 15,
      energyType: 'Rede elétrica',
      depthMeters: 180,
      latitude: -7.5748,
      longitude: -39.3042,
      lastReading: '14/05/2026 09:20',
      notes: 'Queda de vazão em acompanhamento.',
      createdAt: defaultTimestamp,
      updatedAt: defaultTimestamp,
    },
    {
      id: 'well-serra-boa',
      code: 'POC-014',
      category: 'poço',
      name: 'Sítio Serra Boa',
      location: 'Zona 2 - Serra Boa',
      status: 'operando',
      responsible: 'Técnico de Campo',
      flowRate: 91,
      reservoirLevel: 81,
      powerHp: 12,
      energyType: 'Solar',
      depthMeters: 162,
      latitude: -7.6119,
      longitude: -39.2533,
      lastReading: '14/05/2026 08:55',
      notes: 'Operação estável.',
      createdAt: defaultTimestamp,
      updatedAt: defaultTimestamp,
    },
  ],
  bomba: [
    {
      id: 'pump-sp-17-10',
      code: 'BMB-012',
      category: 'bomba',
      name: 'Bomba SP 17-10',
      location: 'Estação Centro',
      status: 'manutenção',
      responsible: 'Técnico de Campo',
      flowRate: 0,
      powerHp: 15,
      energyType: 'Trifásica',
      latitude: -7.5812,
      longitude: -39.282,
      lastReading: '13/05/2026 17:40',
      notes: 'Troca de rolamento programada.',
      createdAt: defaultTimestamp,
      updatedAt: defaultTimestamp,
    },
  ],
  reservatório: [
    {
      id: 'reservoir-sao-francisco',
      code: 'RES-003',
      category: 'reservatório',
      name: 'Reservatório São Francisco',
      location: 'Zona 3 - São Francisco',
      status: 'operando',
      responsible: 'Gestor Hídrico',
      flowRate: 64,
      reservoirLevel: 86,
      capacityM3: 420,
      latitude: -7.5632,
      longitude: -39.2684,
      lastReading: '14/05/2026 09:10',
      notes: 'Nível regular para a faixa operacional.',
      createdAt: defaultTimestamp,
      updatedAt: defaultTimestamp,
    },
  ],
  localidade: [
    {
      id: 'locality-centro',
      code: 'LOC-001',
      category: 'localidade',
      name: 'Jardim Centro',
      location: 'Sede municipal',
      status: 'operando',
      responsible: 'Administração Central',
      flowRate: 64,
      reservoirLevel: 78,
      capacityM3: 420,
      latitude: -7.576,
      longitude: -39.2826,
      lastReading: '14/05/2026 09:05',
      notes: 'Zona com telemetria simulada ativa.',
      createdAt: defaultTimestamp,
      updatedAt: defaultTimestamp,
    },
  ],
};
