import type { Alert, ChartPoint, HydroRegistry, Maintenance } from './types';

const defaultTimestamp = '2026-05-14T12:00:00.000Z';

export const defaultHydroRegistry: HydroRegistry = {
  poço: [
    {
      id: 'well-brejinho',
      code: 'POC-001',
      category: 'poço',
      name: 'Poço Brejinho',
      location: 'Zona 1 - Brejinho',
      status: 'atenção',
      responsible: 'Operador Hidráulico',
      flowRate: 72,
      reservoirLevel: 68,
      powerHp: 15,
      energyType: 'Rede elétrica',
      depthMeters: 180,
      latitude: -7.5748,
      longitude: -39.3042,
      lastReading: '14/05/2026 09:20',
      notes: 'Queda de vazão em acompanhamento.',
      createdAt: defaultTimestamp,
      updatedAt: defaultTimestamp,
    },
    {
      id: 'well-serra-boa',
      code: 'POC-014',
      category: 'poço',
      name: 'Sítio Serra Boa',
      location: 'Zona 2 - Serra Boa',
      status: 'operando',
      responsible: 'Técnico de Campo',
      flowRate: 91,
      reservoirLevel: 81,
      powerHp: 12,
      energyType: 'Solar',
      depthMeters: 162,
      latitude: -7.6119,
      longitude: -39.2533,
      lastReading: '14/05/2026 08:55',
      notes: 'Operação estável.',
      createdAt: defaultTimestamp,
      updatedAt: defaultTimestamp,
    },
  ],
  bomba: [
    {
      id: 'pump-sp-17-10',
      code: 'BMB-012',
      category: 'bomba',
      name: 'Bomba SP 17-10',
      location: 'Estação Centro',
      status: 'manutenção',
      responsible: 'Técnico de Campo',
      flowRate: 0,
      powerHp: 15,
      energyType: 'Trifásica',
      latitude: -7.5812,
      longitude: -39.282,
      lastReading: '13/05/2026 17:40',
      notes: 'Troca de rolamento programada.',
      createdAt: defaultTimestamp,
      updatedAt: defaultTimestamp,
    },
  ],
  reservatório: [
    {
      id: 'reservoir-sao-francisco',
      code: 'RES-003',
      category: 'reservatório',
      name: 'Reservatório São Francisco',
      location: 'Zona 3 - São Francisco',
      status: 'operando',
      responsible: 'Gestor Hídrico',
      flowRate: 64,
      reservoirLevel: 86,
      capacityM3: 420,
      latitude: -7.5632,
      longitude: -39.2684,
      lastReading: '14/05/2026 09:10',
      notes: 'Nível regular para a faixa operacional.',
      createdAt: defaultTimestamp,
      updatedAt: defaultTimestamp,
    },
  ],
  localidade: [
    {
      id: 'locality-centro',
      code: 'LOC-001',
      category: 'localidade',
      name: 'Jardim Centro',
      location: 'Sede municipal',
      status: 'operando',
      responsible: 'Administração Central',
      flowRate: 64,
      reservoirLevel: 78,
      capacityM3: 420,
      latitude: -7.576,
      longitude: -39.2826,
      lastReading: '14/05/2026 09:05',
      notes: 'Zona com telemetria simulada ativa.',
      createdAt: defaultTimestamp,
      updatedAt: defaultTimestamp,
    },
  ],
};

export const alerts: Alert[] = [
  {
    id: 'ALT-001',
    title: 'Queda de vazão acentuada',
    source: 'Poço Brejinho',
    severity: 'critical',
    time: 'há 18 min',
  },
  {
    id: 'ALT-002',
    title: 'Manutenção vencida',
    source: 'Bomba SP 17-10',
    severity: 'warning',
    time: 'hoje',
  },
  {
    id: 'ALT-003',
    title: 'Poço sem atualização',
    source: 'São Francisco',
    severity: 'warning',
    time: 'há 2h',
  },
];

export const maintenances: Maintenance[] = [
  {
    id: 'OS-2401',
    asset: 'Bomba SP 17-10',
    service: 'Troca de rolamento',
    profile: 'Técnico de Campo',
    dueIn: '1 dia',
    status: 'manutenção',
  },
  {
    id: 'OS-2402',
    asset: 'Poço Brejinho',
    service: 'Verificação de queda de vazão',
    profile: 'Operador Hidráulico',
    dueIn: 'Hoje',
    status: 'atenção',
  },
  {
    id: 'OS-2403',
    asset: 'Reservatório São Francisco',
    service: 'Inspeção preventiva',
    profile: 'Gestor Hídrico',
    dueIn: '5 dias',
    status: 'operando',
  },
];

export const flowSeries: ChartPoint[] = [
  { label: 'Seg', value: 118 },
  { label: 'Ter', value: 142 },
  { label: 'Qua', value: 132 },
  { label: 'Qui', value: 146 },
  { label: 'Sex', value: 121 },
  { label: 'Sáb', value: 154 },
  { label: 'Dom', value: 139 },
];

export const productionSeries: ChartPoint[] = [
  { label: 'Jan', value: 62 },
  { label: 'Fev', value: 68 },
  { label: 'Mar', value: 71 },
  { label: 'Abr', value: 76 },
  { label: 'Mai', value: 82 },
  { label: 'Jun', value: 88 },
];
